name: Render paper.pdf
on: push
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3

      - name: Get Source Han Serif font
        run: |
          wget https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/09_SourceHanSerifSC.zip
          unzip 09_SourceHanSerifSC.zip
      - run: typst compile paper.typ paper.pdf --font-path ./OTF/SimplifiedChinese/
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
